# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6976ad259dfdc29b455dc37e3f41bc670769e6f7aff081f2bd64dd4ae49df63eb6bce1386bd207cf6b4c770b4c2f64766b37d42e3a0e6f5aeef881041aca5ec

test:
  secret_key_base: 8bebb4bc448a9aa88315b4fb45905a3e0be35a8bda553e7dc653b5262cf300bf04a0116e179011c6c651c023d1ec92430733c9c516efdbcd8298dccf779cba89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
